### PR TITLE
Update sql2012.smo package

### PR DESCRIPTION
**Pull request by skyguy94**
This PR updates the sql2012.smo package with the latest chocolatey requirements/techniques.
- Adds checksums for 32 and 64 bit packages. The package won't install by default without the checksums.
- Removes the deprecated chocolatey error handling.
- Removes the custom uninstall logic in favor of the built-in chocolatey uninstaller.

If you aren't interested in submitting this, please ask the chocolatey team to add me as a maintainer. I'll happily go through the verification process and address any issues.

### CODE REVIEW

**Comment by taliesins** [comment]
https://chocolatey.org/packages/SQL2012.SMO/11.0.2100.61

**Comment by skyguy94** [comment]
It looks like this failed due to the dependencies not having checksums. Maybe resubmit after those are approved?

**Comment by taliesins** [comment]
I forgot to thank you for pull request. Thank you :-)I will resubmit once it's been approved. I thought it was possible to link to packages that have not yet been moderated.They do seem to take ages to do so.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [taliesins/SQL2012.SMO] Update sql2012.smo package (#2)From: Ritch Melton To: "taliesins/SQL2012.SMO" CC: Taliesin Sisson ,State change It looks like this failed due to the dependencies not having checksums. Maybe resubmit after those are approved?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/taliesins/SQL2012.SMO","title":"taliesins/SQL2012.SMO","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/taliesins/SQL2012.SMO"}},"updates":{"snippets":[{"icon":"PERSON","message":"@skyguy94 in #2: It looks like this failed due to the dependencies not having checksums. Maybe resubmit after those are approved?"}],"action":{"name":"View Pull Request","url":"https://github.com/taliesins/SQL2012.SMO/pull/2#issuecomment-249618890"}}}

**Comment by skyguy94** [comment]
Happy to do it. No thanks necessary! It does take ages to get things approved. I think they're somewhat backlogged again due to the mandatory hash implementation. At least its not as a bad as it was a year ago.

**Comment by skyguy94** [comment]
@taliesins It looks like the other two got approved. You want to try a resubmit on this?

**Comment by taliesins** [comment]
I have finally resubmitted. It seems to have passed test. Hopefully it will show up soon

**Comment by skyguy94** [comment]
Fantastic. ty!

**Pull request merged**
